---
title: "Creating the ``r params$package_name`` R package"
author: "Sheng Jiang, Penghui Fu, Yi Xu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
knit: litr::render
output: litr::litr_gitbook
params:
  package_name: "eivGP" # <-- change this to your package name
package_parent_dir: "." # <-- relative to this file's location
documentclass: book
---
  
# Introduction
  
This package implements `eivGP`, a Errors-in-variables Gaussian processes for 
mixed-input regression. The documentation and
package are both created using one simple command:
  
```{r render, eval = FALSE}
litr::render("index.Rmd", output_format = litr::litr_gitbook())
install.packages("~/repos/eivGP/eivGP", type='source',repos=NULL)
## install.packages("./eivGP/", repos = NULL, type="source")
```

This line is purely for testing (to be deleted later!).

```{r, eval = FALSE}
litr::load_all("index.Rmd")##, output_format = litr::litr_gitbook())
my_load <- function(){litr::render("~/repos/eivGP/index.Rmd", output_format = litr::litr_gitbook(minimal_eval = TRUE))
devtools::load_all("~/repos/eivGP/eivGP")
}
my_load()
devtools::check("~/repos/eivGP/eivGP", document = FALSE)
```